// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Navigation is an autogenerated mock type for the Navigation type
type Navigation struct {
	mock.Mock
}

type Navigation_Expecter struct {
	mock *mock.Mock
}

func (_m *Navigation) EXPECT() *Navigation_Expecter {
	return &Navigation_Expecter{mock: &_m.Mock}
}

// IsOffline provides a mock function with given fields:
func (_m *Navigation) IsOffline() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Navigation_IsOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOffline'
type Navigation_IsOffline_Call struct {
	*mock.Call
}

// IsOffline is a helper method to define mock.On call
func (_e *Navigation_Expecter) IsOffline() *Navigation_IsOffline_Call {
	return &Navigation_IsOffline_Call{Call: _e.mock.On("IsOffline")}
}

func (_c *Navigation_IsOffline_Call) Run(run func()) *Navigation_IsOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Navigation_IsOffline_Call) Return(_a0 bool) *Navigation_IsOffline_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewNavigation interface {
	mock.TestingT
	Cleanup(func())
}

// NewNavigation creates a new instance of Navigation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNavigation(t mockConstructorTestingTNewNavigation) *Navigation {
	mock := &Navigation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
